### ISSUE TITLE
add gaya images

### ISSUE THREAD

**Issue by prudhomm** [feelpp/benchmarking.toolboxes#58]
gaya does not have any images for now
we need to add them

**Comment by tanguypierre** [comment]
@prudhomm 
Couldn't find anything on the web.

Should we take this one from cemosis ?
![cemosis](https://github.com/user-attachments/assets/9212a57d-82f2-4765-bebe-510f062b13ed)

**Comment by prudhomm** [comment]
This has been done in another branch
